export const cricketRules = [
  'Teams will be formed by the event organisers',
  'Each Team should contain 10 players, players AGE should be above 13 years',
  'Each side will get 6 overs to play',
  'Overs follow, single player can bowl 2 OVERS maximum',
  'Ground size will be 40 yards[Short Boundary], hitting outside the boundary will be considered as OUT',
  'There will be one power-play for each innings, where six hitting is active',
  'Minimum one girl player should be included in each Team',
  'Dress Code: Jersey type shirt and track pants, compulsory to wear sports shoes',
  'No Restrictions for the Bowling action',
  'If Team players are not available at the match time, that particular match would be considered as walk-over',
  'From each Group 2 teams would be qualified for the semi-finals, based on NRR and points',
  'Umpire descisions will be FINAL',
  'Any Mis-behaviour or unethical activity observed, the person or the entire team will be DIS-QUALIFIED from the tournament ',
];
